#!/usr/bin/env bash
# Compare the pinned MuJoCo / Godot / godot-cpp versions against the latest
# upstream releases and report which are out of date.
#
# - Human-readable report goes to stdout (and $GITHUB_STEP_SUMMARY when set).
# - `has_updates=true|false` is written to $GITHUB_OUTPUT when set.
# - A Markdown issue body is written to $GMJ_BODY_FILE when set.
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# --- currently pinned versions -------------------------------------------
# shellcheck source=scripts/pinned_versions.sh
source "$ROOT/scripts/pinned_versions.sh"
cur_mujoco="$MUJOCO_VERSION"
cur_godotcpp="$GODOT_CPP_TAG"
cur_godot="$GODOT_VERSION"

gh_json() {
  curl -fsSL -H "Accept: application/vnd.github+json" \
    ${GH_TOKEN:+-H "Authorization: Bearer $GH_TOKEN"} "$1"
}

# --- latest upstream versions --------------------------------------------
latest_mujoco="$(gh_json 'https://api.github.com/repos/google-deepmind/mujoco/releases/latest' \
  | grep -oP '"tag_name":\s*"\K[^"]+' | head -1)"
latest_godot="$(gh_json 'https://api.github.com/repos/godotengine/godot/releases/latest' \
  | grep -oP '"tag_name":\s*"\K[^"]+' | head -1)"
latest_godotcpp="$(git ls-remote --tags https://github.com/godotengine/godot-cpp.git 'godot-*-stable' 2>/dev/null \
  | awk -F/ '{print $NF}' | grep -v '\^{}' | sort -V | tail -1)"

row() { # name current latest
  if [ -z "$3" ]; then
    printf '| %s | `%s` | (lookup failed) | ❓ |\n' "$1" "$2"
  elif [ "$2" = "$3" ]; then
    printf '| %s | `%s` | `%s` | ✅ |\n' "$1" "$2" "$3"
  else
    printf '| %s | `%s` | `%s` | ⬆️ update |\n' "$1" "$2" "$3"
  fi
}

has_updates=false
outdated() { [ -n "$2" ] && [ "$1" != "$2" ]; }
if outdated "$cur_mujoco" "$latest_mujoco" \
  || outdated "$cur_godot" "$latest_godot" \
  || outdated "$cur_godotcpp" "$latest_godotcpp"; then
  has_updates=true
fi

body="$(cat <<EOF
## Upstream dependency versions

| Dependency | Pinned | Latest | Status |
| --- | --- | --- | --- |
$(row "MuJoCo" "$cur_mujoco" "$latest_mujoco")
$(row "Godot" "$cur_godot" "$latest_godot")
$(row "godot-cpp" "$cur_godotcpp" "$latest_godotcpp")

**Updates available: $has_updates**

When bumping, update every pin together and re-run CI:
- **MuJoCo**: \`MUJOCO_VERSION\` + the pinned \`SHA256\` values in \`CMakeLists.txt\`. Reconfigure so \`cmake/godot_mujoco.gdextension.in\` regenerates the addon manifest. CI reads the version from CMake — do not hardcode it in workflows.
- **Godot**: \`GODOT_VERSION\` in \`scripts/cloud_setup.sh\` and \`config/features\` in \`demo/project.godot\`. CI downloads via \`scripts/pinned_versions.sh\`.
- **godot-cpp**: \`GODOT_CPP_TAG\` in \`CMakeLists.txt\` (only when a newer \`godot-*-stable\` branch exists).

_Generated by \`scripts/check_upstream_versions.sh\`._
EOF
)"

echo "$body"
if [ -n "${GITHUB_STEP_SUMMARY:-}" ]; then echo "$body" >> "$GITHUB_STEP_SUMMARY"; fi
if [ -n "${GMJ_BODY_FILE:-}" ]; then echo "$body" > "$GMJ_BODY_FILE"; fi
if [ -n "${GITHUB_OUTPUT:-}" ]; then echo "has_updates=$has_updates" >> "$GITHUB_OUTPUT"; fi
